#!/usr/bin/env bash
# https://github.com/olivergondza/bash-strict-mode
set -euo pipefail
trap 's=$?; echo >&2 "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

if [ "$#" -eq 0 ]; then
  profile="detailed"
else
  profile="$1"
fi
profile_path="${DIR}/jfc/${profile}"
if [ ! -f "$profile_path" ]; then
  echo >&2 "profile does not exist ${profile_path}"
  exit 1
fi

echo -DargLine="-XX:+UnlockCommercialFeatures -XX:+FlightRecorder -XX:FlightRecorderOptions=samplethreads=true -XX:StartFlightRecording=dumponexit=true,filename=$(pwd)/surefire.jfr,settings=${profile_path}"
